name: backend_unit_test_action

on:
  push:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: sudo apt-get update && sudo apt-get upgrade
      - run: sudo apt-get install libmysqlclient-dev
      - run: pip install -r requirements.txt
      - run: python main.py unit-test